postgres:
  user: admin
  password: admin123
  connectionHost: postgres_privelege
  port: 5432
  database_name: privelege
  sslmode: disable

server: 
  address: :8010
  write_timeout: 5s
  read_timeout: 5s
  idle_timeout: 3s
  shutdown_duration: 10s