postgres:
  user: admin
  password: admin123
  connectionHost: localhost
  port: 5432
  database_name: health
  sslmode: disable

server: 
  address: localhost:8010
  write_timeout: 5s
  read_timeout: 5s
  idle_timeout: 3s
  shutdown_duration: 10s